[package]
name = "umbra"
version = "0.1.0"
authors = ["Travis Finkenauer <tmfinken@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4"
fern = "0.5"
hyper = "0.12"
log = "0.4"

[dependencies.clap]
version = "2.32"
default-features = false
features = [ "suggestions" ]
